use neo4rs::*;
use futures::stream::*;
use rpassword::read_password;
use std::io::{self, prelude::*};
use indicatif::ProgressBar;
use std::collections::HashSet;
use std::collections::HashMap;

pub mod load {
    // Load module code
}

#[derive(Debug)]
struct GroupedData {
    earliest_date: String, // Assuming the date is in String format
    count: usize,
}

// ───────── helper (inline or place it above) ─────────────────────────
fn looks_like_ip(s: &str) -> bool {
    // IPv4 → only digits + dots; IPv6 → hex digits + colons
    let ipv4 = s.chars().all(|c| c.is_ascii_digit() || c == '.');
    let ipv6 = s.chars().all(|c| c.is_ascii_hexdigit() || c == ':');
    ipv4 || ipv6
}

// ── helper: returns the (sub-)slice that contains the leading IPv4/IPv6, if any
fn extract_leading_ip<'a>(s: &'a str) -> Option<&'a str> {
    // take chars while they are digits, dots, or colons
    let candidate = s
        .chars()
        .take_while(|c| c.is_ascii_digit() || *c == '.' || *c == ':')
        .collect::<String>();

    // quick tests: at least one dot for IPv4 or one colon for IPv6
    if candidate.contains('.') || candidate.contains(':') {
        Some(&s[..candidate.len()])
    } else {
        None
    }
}

pub async fn load_neo4j(files: &Vec<String>, database: &String, user: &String) {
    let start_clock = std::time::Instant::now();

    // Phase 1: Connect
    crate::banner::print_phase("1", "2", "Connecting to Neo4j...");
    crate::banner::print_phase_detail("Database:", database);
    let pass = rpassword::prompt_password("MASSTIN - Enter Neo4j database password: ").unwrap();
    let graph = Graph::new(database, user, &pass).await.unwrap();
    crate::banner::print_phase_result("Connected");

    for file in files {
        let file_contents: String = std::fs::read_to_string(file).unwrap();
        let mut lines: Vec<&str> = file_contents.lines().collect();

        // Verify the file header (support both old and new format)
        let old_header = "time_created,dst_computer,event_id,subject_user_name,subject_domain_name,target_user_name,target_domain_name,logon_type,src_computer,src_ip,process,log_filename";
        let new_header = "time_created,dst_computer,event_type,event_id,logon_type,target_user_name,target_domain_name,src_computer,src_ip,subject_user_name,subject_domain_name,logon_id,detail,log_filename";
        let is_new_format = lines.get(0).map(|h| *h == new_header).unwrap_or(false);
        let is_old_format = lines.get(0).map(|h| *h == old_header).unwrap_or(false);
        if lines.is_empty() || (!is_new_format && !is_old_format) {
            println!("MASSTIN - File {} has not been generated by Masstin", file);
            continue;
        }

        // Column index mapping
        // New: 0=time, 1=dst, 2=event_type, 3=event_id, 4=logon_type, 5=target_user, 6=target_domain, 7=src_computer, 8=src_ip, 9=subject_user, 10=subject_domain, 11=logon_id, 12=detail, 13=log_filename
        // Old: 0=time, 1=dst, 2=event_id, 3=subject_user, 4=subject_domain, 5=target_user, 6=target_domain, 7=logon_type, 8=src_computer, 9=src_ip, 10=process, 11=log_filename
        let (idx_dst, idx_subject_user, idx_subject_domain, idx_target_user, idx_target_domain, idx_logon_type, idx_src_computer, idx_src_ip) = if is_new_format {
            (1usize, 9usize, 10usize, 5usize, 6usize, 4usize, 7usize, 8usize)
        } else {
            (1usize, 3usize, 4usize, 5usize, 6usize, 7usize, 8usize, 9usize)
        };

        let local_values: HashSet<&str> = 
                ["LOCAL", "127.0.0.1", "::1", "DEFAULT_VALUE", "\"\"", "-", ""," ",]
                .iter().cloned().collect();

        let processed_lines: Vec<String> = lines
        .into_iter()
        .skip(1)
        .map(|line| line.replace("\\", "").replace("[", "").replace("]", "").to_uppercase())
        .filter_map(|line| {
            let mut row: Vec<&str> = line.split(',').collect();
            row.pop();

            // dst_computer
            if let Some(ip) = extract_leading_ip(row[idx_dst]) {
                row[idx_dst] = ip;
            } else if row[idx_dst].contains('.') && !looks_like_ip(row[idx_dst]) {
                row[idx_dst] = row[idx_dst].split('.').next().unwrap_or(row[idx_dst]);
            }

            // src_computer
            if let Some(ip) = extract_leading_ip(row[idx_src_computer]) {
                row[idx_src_computer] = ip;
            } else if row[idx_src_computer].contains('.') && !looks_like_ip(row[idx_src_computer]) {
                row[idx_src_computer] = row[idx_src_computer].split('.').next().unwrap_or(row[idx_src_computer]);
            }

            // src_ip
            if let Some(ip) = extract_leading_ip(row[idx_src_ip]) {
                row[idx_src_ip] = ip;
            } else if row[idx_src_ip].contains('.') && !looks_like_ip(row[idx_src_ip]) {
                row[idx_src_ip] = row[idx_src_ip].split('.').next().unwrap_or(row[idx_src_ip]);
            }

            if row[idx_dst].contains(':') {
                row[idx_dst] = row[idx_dst].split(':').next().unwrap_or(row[idx_dst]);
            }

            if row[idx_src_computer].contains(':') {
                row[idx_src_computer] = row[idx_src_computer].split(':').next().unwrap_or(row[idx_dst]);
            }

            if row[idx_src_ip].contains(':') {
                row[idx_src_ip] = row[idx_src_ip].split(':').next().unwrap_or(row[idx_dst]);
            }

            if local_values.contains(&row[idx_src_computer]) && local_values.contains(&row[idx_src_ip]) {
                None
            } else if row[idx_dst] == row[idx_src_computer] {
                None
            } else if row[idx_dst] == row[idx_src_ip] {
                None
            } else {
                Some(row.join(","))
            }
        })
        .collect();

        let mut grouped_map: HashMap<(String, String, String, String, String, String, String, String), GroupedData> = HashMap::new();
        let mut counts: HashMap<(String, String), u32> = HashMap::new();

        for line in processed_lines {
            let parts: Vec<String> = line.split(',').map(|s| s.to_string()).collect();

            if !local_values.contains(parts[idx_src_computer].as_str()) && !local_values.contains(parts[idx_src_ip].as_str()) && parts[idx_src_computer] != parts[idx_src_ip] {
                *counts.entry((parts[idx_src_ip].clone(), parts[idx_src_computer].clone())).or_insert(0) += 1;
            }
            // Group by: dst_computer, subject_user_name, subject_domain_name, target_user_name, target_domain_name, logon_type, src_computer, src_ip
            let key = (parts[idx_dst].clone(), parts[idx_subject_user].clone(), parts[idx_subject_domain].clone(), parts[idx_target_user].clone(), parts[idx_target_domain].clone(), parts[idx_logon_type].clone(), parts[idx_src_computer].clone(), parts[idx_src_ip].clone());
            let date = parts[0].clone();

            let entry = grouped_map.entry(key).or_insert(GroupedData {
                earliest_date: date.clone(),
                count: 0,
            });

            if date < entry.earliest_date {
                entry.earliest_date = date;
            }
            entry.count += 1;
        }

        // Convert the HashMap to a vector of strings
        // Output format: date, dst_computer, count, subject_user, subject_domain, target_user, target_domain, logon_type, src_computer, src_ip
        let mut grouped_lines: Vec<String> = Vec::new();
        for ((dst_computer, subject_user_name, subject_domain_name, target_user_name, target_domain_name, logon_type, src_computer, src_ip), data) in grouped_map {
            grouped_lines.push(format!("{},{},{},{},{},{},{},{},{},{}", data.earliest_date, dst_computer, data.count, subject_user_name, subject_domain_name, target_user_name, target_domain_name, logon_type, src_computer, src_ip));
        }

        // Phase 2: Load to database
        let grouped_lines_count = grouped_lines.len();
        crate::banner::print_phase("2", "2", &format!("Loading {} grouped connections to Neo4j...", grouped_lines_count));
        let pb = crate::banner::create_progress_bar(grouped_lines_count as u64);
        let mut errors: usize = 0;
        let mut resolved: usize = 0;

        for line in grouped_lines {
            let mut row: Vec<&str> = line.split(',').collect();
            let relation_type = if row[5].trim().is_empty() || row[5] == "\"\"" { "NO_USER" } else { &row[5] };
            let mut hostname = row[8];
            if local_values.contains(row[8]) || counts.iter().any(|((ip, _), _)| ip == &row[9]) {
                // Filter the HashMap entries to find those matching the target_ip
                let filtered_counts: Vec<(&(String, String), &u32)> = counts.iter()
                .filter(|&((ip, _), _)| ip == row[9])
                .collect();
                
                // Find the entry with the highest count
                if let Some(((_, most_frequent_value), &_count)) = filtered_counts.iter()
                    .max_by_key(|&(_, &count)| count) {
                    resolved += 1;
                    hostname = most_frequent_value;
                } else {
                    hostname = row[9];
                }
            }
            
            // Relationship type must be a valid Cypher identifier:
            // replace dots, hyphens, spaces with underscores; uppercase; strip @domain
            let rel_type_normalized = {
                let r = if relation_type.chars().next().unwrap_or(' ').is_ascii_digit() {
                    format!("u{}", relation_type)
                } else {
                    relation_type.to_string()
                };
                r.replace(".", "_").replace("-", "_").replace(" ", "_")
                    .split("@").next().unwrap_or(&r).to_uppercase()
            };

            // Node names and properties: keep original values (no normalization)
            // Only strip @domain from usernames
            let clean_user = |s: &str| -> String {
                s.split("@").next().unwrap_or(s).to_string()
            };

            let formatted_query = format!(
                "MERGE (origin:host{{name:'{}'}})
                MERGE (destination:host{{name:'{}'}})
                MERGE (origin)-[r:{}{{time:datetime('{}'), logon_type:'{}', src_computer:'{}', src_ip:'{}', target_user_name:'{}', target_domain_name:'{}', subject_user_name:'{}', subject_domain_name:'{}', count:'{}'}}]->(destination)",
                hostname,                                                    // node: original
                row[1],                                                      // node: original
                rel_type_normalized,                                         // rel type: normalized (Cypher requirement)
                row[0].replace(" utc", "").replace(" ", "T"),
                row[7],                                                      // property: original
                row[8],                                                      // property: original
                row[9],                                                      // property: original
                clean_user(relation_type),                                   // property: strip @domain only
                row[6],                                                      // property: original
                clean_user(row[3]),                                          // property: strip @domain only
                row[4],                                                      // property: original
                row[2],                                                      // property: original
            );
            
            // Execute the query and handle possible errors
            match graph.execute(query(&formatted_query)).await {
                Ok(mut result) => {
                    let row = result.next().await.unwrap();  // Process the result
                    // You can add more logic here if you need to process the result
                },
                Err(e) => {
                    errors += 1;
                    if crate::parse::is_debug_mode() {
                        eprintln!("[ERROR] Cypher query failed: {:?}", e);
                    }
                    continue;
                }
            }

            // Increment the progress bar
            pb.inc(1);
        }

        pb.finish_and_clear();
        let loaded = grouped_lines_count - errors;
        crate::banner::print_load_summary("Neo4j", loaded, resolved, errors, start_clock);
    }
}
