use neo4rs::*;
use futures::stream::*;
use indicatif::ProgressBar;
use std::collections::HashSet;
use std::collections::HashMap;
use chrono::{DateTime, Utc, NaiveDateTime, TimeZone};

/// Parse a user-supplied start/end time string (from the CLI flags) into a
/// DateTime<Utc>. Accepts the Cortex flag format `YYYY-MM-DD HH:MM:SS [-0000]`
/// already validated upstream, plus a bare `YYYY-MM-DD HH:MM:SS`.
fn parse_time_window(raw: &str) -> Option<DateTime<Utc>> {
    let trimmed = raw.trim();
    let base = if trimmed.len() >= 19 {
        &trimmed[..19]
    } else {
        trimmed
    };
    NaiveDateTime::parse_from_str(base, "%Y-%m-%d %H:%M:%S")
        .ok()
        .map(|naive| Utc.from_utc_datetime(&naive))
}

/// Parse a CSV `time_created` cell into a DateTime<Utc>. masstin produces
/// several formats depending on the original source (EVTX → ISO 8601 with
/// fractional seconds, Cortex → `YYYY-MM-DD HH:MM:SS.fff UTC`, Linux →
/// `YYYY-MM-DD HH:MM:SS`). We try the common shapes in order.
fn parse_csv_time(raw: &str) -> Option<DateTime<Utc>> {
    let s = raw.trim();
    if s.is_empty() { return None; }
    if let Ok(dt) = DateTime::parse_from_rfc3339(s) {
        return Some(dt.with_timezone(&Utc));
    }
    if let Ok(dt) = NaiveDateTime::parse_from_str(s.trim_end_matches(" UTC"), "%Y-%m-%d %H:%M:%S%.f") {
        return Some(Utc.from_utc_datetime(&dt));
    }
    if let Ok(dt) = NaiveDateTime::parse_from_str(s.trim_end_matches('Z'), "%Y-%m-%dT%H:%M:%S%.f") {
        return Some(Utc.from_utc_datetime(&dt));
    }
    if let Ok(dt) = NaiveDateTime::parse_from_str(s, "%Y-%m-%d %H:%M:%S") {
        return Some(Utc.from_utc_datetime(&dt));
    }
    None
}

pub mod load {
    // Load module code
}

#[derive(Debug)]
struct GroupedData {
    earliest_date: String,
    count: usize,
    // Non-key fields: stored from the first row seen for this group
    subject_user: String,
    subject_domain: String,
    target_domain: String,
    src_computer: String,
    src_ip: String,
}

/// Strip timezone suffix for Memgraph localDateTime().
/// Handles: "Z", "+00:00", "-05:00", etc.
fn strip_timezone(ts: &str) -> String {
    let ts = ts.trim_end_matches('Z');
    if ts.len() > 6 {
        let tail = &ts[ts.len()-6..];
        if (tail.starts_with('+') || tail.starts_with('-')) && tail.contains(':') {
            return ts[..ts.len()-6].to_string();
        }
    }
    ts.to_string()
}

fn looks_like_ip(s: &str) -> bool {
    let ipv4 = s.chars().all(|c| c.is_ascii_digit() || c == '.');
    let ipv6 = s.chars().all(|c| c.is_ascii_hexdigit() || c == ':');
    ipv4 || ipv6
}

fn extract_leading_ip<'a>(s: &'a str) -> Option<&'a str> {
    let candidate = s
        .chars()
        .take_while(|c| c.is_ascii_digit() || *c == '.' || *c == ':')
        .collect::<String>();

    if candidate.contains('.') || candidate.contains(':') {
        Some(&s[..candidate.len()])
    } else {
        None
    }
}

pub async fn load_memgraph(
    files: &Vec<String>,
    database: &String,
    user: &String,
    ungrouped: bool,
    start_time: Option<&String>,
    end_time: Option<&String>,
) {
    let start_clock = std::time::Instant::now();

    // Phase 1: Connect
    crate::banner::print_phase("1", "2", "Connecting to Memgraph...");
    crate::banner::print_phase_detail("Database:", database);
    if ungrouped {
        crate::banner::print_phase_detail("Mode:", "UNGROUPED (one edge per CSV row)");
    }
    if let Some(s) = start_time {
        crate::banner::print_phase_detail("Start time:", s);
    }
    if let Some(e) = end_time {
        crate::banner::print_phase_detail("End time:", e);
    }
    let config = ConfigBuilder::default()
        .uri(database)
        .user(user)
        .password("")
        .db("memgraph")
        .build()
        .unwrap();
    let graph = Graph::connect(config).await.unwrap();
    crate::banner::print_phase_result("Connected");

    let start_dt = start_time.and_then(|s| parse_time_window(s));
    let end_dt = end_time.and_then(|s| parse_time_window(s));

    for file in files {
        let file_contents: String = std::fs::read_to_string(file).unwrap();
        let mut lines: Vec<&str> = file_contents.lines().collect();

        // Verify the file header (support both old and new format)
        let old_header = "time_created,dst_computer,event_id,subject_user_name,subject_domain_name,target_user_name,target_domain_name,logon_type,src_computer,src_ip,process,log_filename";
        let new_header = "time_created,dst_computer,event_type,event_id,logon_type,target_user_name,target_domain_name,src_computer,src_ip,subject_user_name,subject_domain_name,logon_id,detail,log_filename";
        let is_new_format = lines.get(0).map(|h| *h == new_header).unwrap_or(false);
        let is_old_format = lines.get(0).map(|h| *h == old_header).unwrap_or(false);
        if lines.is_empty() || (!is_new_format && !is_old_format) {
            println!("MASSTIN - File {} has not been generated by Masstin", file);
            continue;
        }

        // Column index mapping
        let (idx_dst, idx_event_id, idx_subject_user, idx_subject_domain, idx_target_user, idx_target_domain, idx_logon_type, idx_src_computer, idx_src_ip) = if is_new_format {
            (1usize, 3usize, 9usize, 10usize, 5usize, 6usize, 4usize, 7usize, 8usize)
        } else {
            (1usize, 2usize, 3usize, 4usize, 5usize, 6usize, 7usize, 8usize, 9usize)
        };

        let local_values: HashSet<&str> =
                ["LOCAL", "127.0.0.1", "::1", "::", "0.0.0.0", "DEFAULT_VALUE", "\"\"", "-", ""," ",]
                .iter().cloned().collect();

        let mut filtered_by_time: usize = 0;

        let processed_lines: Vec<String> = lines
        .into_iter()
        .skip(1)
        .map(|line| line.replace("\\", "").replace("[", "").replace("]", "").to_uppercase())
        .filter_map(|line| {
            if start_dt.is_some() || end_dt.is_some() {
                if let Some(time_cell) = line.split(',').next() {
                    if let Some(row_dt) = parse_csv_time(time_cell) {
                        if let Some(start) = start_dt {
                            if row_dt < start { filtered_by_time += 1; return None; }
                        }
                        if let Some(end) = end_dt {
                            if row_dt > end { filtered_by_time += 1; return None; }
                        }
                    }
                }
            }

            let mut row: Vec<&str> = line.split(',').collect();
            row.pop();

            if let Some(ip) = extract_leading_ip(row[idx_dst]) {
                row[idx_dst] = ip;
            } else if row[idx_dst].contains('.') && !looks_like_ip(row[idx_dst]) {
                row[idx_dst] = row[idx_dst].split('.').next().unwrap_or(row[idx_dst]);
            }

            if let Some(ip) = extract_leading_ip(row[idx_src_computer]) {
                row[idx_src_computer] = ip;
            } else if row[idx_src_computer].contains('.') && !looks_like_ip(row[idx_src_computer]) {
                row[idx_src_computer] = row[idx_src_computer].split('.').next().unwrap_or(row[idx_src_computer]);
            }

            if let Some(ip) = extract_leading_ip(row[idx_src_ip]) {
                row[idx_src_ip] = ip;
            } else if row[idx_src_ip].contains('.') && !looks_like_ip(row[idx_src_ip]) {
                row[idx_src_ip] = row[idx_src_ip].split('.').next().unwrap_or(row[idx_src_ip]);
            }

            // Strip `hostname:port` / `hostname:instance` suffixes, but preserve
            // IPv6 literals (they are all hex + colons and must never be split).
            if row[idx_dst].contains(':') && !looks_like_ip(row[idx_dst]) {
                row[idx_dst] = row[idx_dst].split(':').next().unwrap_or(row[idx_dst]);
            }

            if row[idx_src_computer].contains(':') && !looks_like_ip(row[idx_src_computer]) {
                row[idx_src_computer] = row[idx_src_computer].split(':').next().unwrap_or(row[idx_src_computer]);
            }

            if row[idx_src_ip].contains(':') && !looks_like_ip(row[idx_src_ip]) {
                row[idx_src_ip] = row[idx_src_ip].split(':').next().unwrap_or(row[idx_src_ip]);
            }

            if local_values.contains(&row[idx_src_computer]) && local_values.contains(&row[idx_src_ip]) {
                None
            } else if row[idx_dst] == row[idx_src_computer] {
                None
            } else if row[idx_dst] == row[idx_src_ip] {
                None
            } else {
                Some(row.join(","))
            }
        })
        .collect();

        if filtered_by_time > 0 {
            crate::banner::print_phase_detail(
                "Time window:",
                &format!("{} rows dropped (outside [start, end] window)", filtered_by_time),
            );
        }

        // ── Frequency map with 4778/4779 priority (x1000 weight) ──
        let mut counts: HashMap<(String, String), u32> = HashMap::new();

        for line in &processed_lines {
            let parts: Vec<String> = line.split(',').map(|s| s.to_string()).collect();

            // ── Direct evidence: (src_ip, src_computer) pair ──
            if !local_values.contains(parts[idx_src_computer].as_str())
                && !local_values.contains(parts[idx_src_ip].as_str())
                && parts[idx_src_computer] != parts[idx_src_ip]
            {
                let weight: u32 = if parts[idx_event_id] == "4778" || parts[idx_event_id] == "4779" {
                    1000
                } else {
                    1
                };
                *counts
                    .entry((parts[idx_src_ip].clone(), parts[idx_src_computer].clone()))
                    .or_insert(0) += weight;
            }

            // ── Machine-account hint: target_user ends in $ → computer name ──
            // On Kerberos AD networks every machine has a computer account
            // MACHINE$. When a 4624 arrives from an IP with src_computer
            // empty and target_user=MACHINE$, that's strong evidence the IP
            // belongs to MACHINE. Weight x100 sits between normal events
            // (x1) and the authoritative 4778/4779 pair (x1000).
            if local_values.contains(parts[idx_src_computer].as_str())
                && !local_values.contains(parts[idx_src_ip].as_str())
            {
                let target_user = parts[idx_target_user].as_str();
                if target_user.ends_with('$') && target_user.len() > 1 {
                    let machine = &target_user[..target_user.len() - 1];
                    // Reject if it still looks like an IP or has invalid chars
                    if !looks_like_ip(machine) && !machine.contains('.') && !machine.is_empty() {
                        *counts
                            .entry((parts[idx_src_ip].clone(), machine.to_string()))
                            .or_insert(0) += 100;
                    }
                }
            }
        }

        // ── Global IP→hostname map ──
        let mut ip_to_host: HashMap<String, String> = HashMap::new();
        {
            let mut best: HashMap<String, (String, u32)> = HashMap::new();
            for ((ip, host), weight) in &counts {
                let entry = best.entry(ip.clone()).or_insert((host.clone(), 0));
                if *weight > entry.1 {
                    *entry = (host.clone(), *weight);
                }
            }
            for (ip, (host, _)) in best {
                ip_to_host.insert(ip, host);
            }
        }

        // ── Edge emission: either grouped or ungrouped ──
        let mut edges_to_emit: Vec<String> = Vec::new();

        if ungrouped {
            for line in &processed_lines {
                let parts: Vec<String> = line.split(',').map(|s| s.to_string()).collect();
                edges_to_emit.push(format!(
                    "{},{},{},{},{},{},{},{},{},{}",
                    parts[0],
                    parts[idx_dst],
                    "1",
                    parts[idx_subject_user],
                    parts[idx_subject_domain],
                    parts[idx_target_user],
                    parts[idx_target_domain],
                    parts[idx_logon_type],
                    parts[idx_src_computer],
                    parts[idx_src_ip],
                ));
            }
        } else {
            // Grouping key: (dst, target_user, logon_type)
            // The resolved origin node is determined downstream by ip_to_host;
            // src_ip is a detail for the CSV, not the graph. Keeping only
            // these 3 fields produces one edge per (origin, user, type, dest).
            let mut grouped_map: HashMap<
                (String, String, String),
                GroupedData,
            > = HashMap::new();

            for line in &processed_lines {
                let parts: Vec<String> = line.split(',').map(|s| s.to_string()).collect();
                // Strip @DOMAIN from target_user before grouping — Kerberos
                // TGS events (4769) append @REALM to the username while 4624
                // events don't, causing duplicate edges for the same user.
                let user_clean = parts[idx_target_user].split('@').next()
                    .unwrap_or(&parts[idx_target_user]).to_string();
                let key = (
                    parts[idx_dst].clone(),
                    user_clean,
                    parts[idx_logon_type].clone(),
                );
                let date = parts[0].clone();
                let entry = grouped_map.entry(key).or_insert(GroupedData {
                    earliest_date: date.clone(),
                    count: 0,
                    subject_user: parts[idx_subject_user].clone(),
                    subject_domain: parts[idx_subject_domain].clone(),
                    target_domain: parts[idx_target_domain].clone(),
                    src_computer: parts[idx_src_computer].clone(),
                    src_ip: parts[idx_src_ip].clone(),
                });
                if date < entry.earliest_date {
                    entry.earliest_date = date;
                }
                entry.count += 1;
            }

            for ((dst_computer, target_user_name, logon_type), data) in grouped_map {
                edges_to_emit.push(format!(
                    "{},{},{},{},{},{},{},{},{},{}",
                    data.earliest_date,
                    dst_computer,
                    data.count,
                    data.subject_user,
                    data.subject_domain,
                    target_user_name,
                    data.target_domain,
                    logon_type,
                    data.src_computer,
                    data.src_ip,
                ));
            }
        }

        // Phase 2: Load to database
        let grouped_lines_count = edges_to_emit.len();
        let phase_label = if ungrouped {
            format!("Loading {} individual edges to Memgraph (ungrouped mode)...", grouped_lines_count)
        } else {
            format!("Loading {} grouped connections to Memgraph...", grouped_lines_count)
        };
        crate::banner::print_phase("2", "2", &phase_label);
        let pb = crate::banner::create_progress_bar(grouped_lines_count as u64);
        let grouped_lines = edges_to_emit;
        let mut errors: usize = 0;
        let mut resolved: usize = 0;

        for line in grouped_lines {
            let row: Vec<&str> = line.split(',').collect();
            let relation_type = if row[5].trim().is_empty() || row[5] == "\"\"" { "NO_USER" } else { row[5] };

            // ── Source-side resolution ──
            // When the parser leaves `src_computer` empty, equal to a local
            // value, OR filled in with the literal IP (which happens on 4624
            // events where WorkstationName was blank and masstin fell back
            // to the address), we try to resolve the real hostname from the
            // global ip_to_host map. That way the same physical host does
            // not end up as two separate nodes (one by hostname, one by IP).
            let src_ip_raw = row[9];
            let src_computer_raw = row[8];
            let src_computer_is_ip = looks_like_ip(src_computer_raw)
                && src_computer_raw == src_ip_raw;
            let needs_resolution = local_values.contains(src_computer_raw) || src_computer_is_ip;
            let origin_name: String = if needs_resolution {
                if let Some(resolved_host) = ip_to_host.get(src_ip_raw) {
                    resolved += 1;
                    resolved_host.clone()
                } else if !local_values.contains(src_ip_raw) {
                    src_ip_raw.to_string()
                } else {
                    pb.inc(1);
                    continue;
                }
            } else {
                src_computer_raw.to_string()
            };

            // ── Destination-side resolution ──
            let dst_raw = row[1];
            let destination_name: String = if looks_like_ip(dst_raw) {
                if let Some(resolved_host) = ip_to_host.get(dst_raw) {
                    resolved_host.clone()
                } else {
                    dst_raw.to_string()
                }
            } else {
                dst_raw.to_string()
            };

            // Self-loop filter: after resolution, drop any edge whose origin
            // and destination point at the same host. Self-loops are pure
            // noise in a lateral-movement graph — they collapse into ugly
            // circular arrows in the viewer and obscure real cross-host
            // movement. We check here (post-resolution) rather than on the
            // raw fields, because resolution itself creates new matches
            // (e.g. 192.168.10.11 → WINTERFELL against dst=WINTERFELL).
            if origin_name.eq_ignore_ascii_case(&destination_name) {
                pb.inc(1);
                continue;
            }

            // Relationship type must be a valid Cypher identifier:
            // [A-Za-z_][A-Za-z0-9_]*. Anything else (`$`, `!`, `(`, `)`, dots,
            // hyphens, spaces, accents...) becomes `_`. The `$` case is the
            // important one — machine accounts like `SPACHE$` would otherwise
            // generate `r:SPACHE$` which Cypher parses as a parameter ref and
            // kills the Bolt session for every query after it.
            let rel_type_normalized = {
                let stripped = relation_type.split('@').next().unwrap_or(relation_type);
                let mut s: String = stripped.chars().map(|c| {
                    if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' }
                }).collect();
                if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
                    s = format!("u{}", s);
                }
                if s.is_empty() { s = "NO_USER".to_string(); }
                s.to_uppercase()
            };

            let clean_user = |s: &str| -> String {
                s.split("@").next().unwrap_or(s).to_string()
            };

            let edge_op = if ungrouped { "CREATE" } else { "MERGE" };

            let formatted_query = format!(
                "MERGE (origin:host{{name:'{}'}})
                MERGE (destination:host{{name:'{}'}})
                {} (origin)-[r:{}{{time:localDateTime('{}'), logon_type:'{}', src_computer:'{}', src_ip:'{}', target_user_name:'{}', target_domain_name:'{}', subject_user_name:'{}', subject_domain_name:'{}', count:'{}'}}]->(destination)",
                origin_name,
                destination_name,
                edge_op,
                rel_type_normalized,
                strip_timezone(&row[0].replace(" utc", "").replace(" ", "T")),
                row[7],
                src_computer_raw,
                src_ip_raw,
                clean_user(relation_type),
                row[6],
                clean_user(row[3]),
                row[4],
                row[2],
            );

            if crate::parse::is_debug_mode() {
                eprintln!("[DEBUG] edge #{}: {}", pb.position() + 1, formatted_query);
            }
            match graph.execute(query(&formatted_query)).await {
                Ok(mut result) => {
                    let row = result.next().await.unwrap();
                },
                Err(e) => {
                    errors += 1;
                    if crate::parse::is_debug_mode() {
                        eprintln!("[ERROR] Cypher query failed: {:?}", e);
                    }
                    continue;
                }
            }

            pb.inc(1);
        }

        pb.finish_and_clear();
        let loaded = grouped_lines_count - errors;
        crate::banner::print_load_summary("Memgraph", loaded, resolved, errors, start_clock);
    }
}
